### PR TITLE
Improve MetaKnowledgeGraphServiceTest tests

### PR DESCRIPTION
**Pull request by gaurav**
This PR improves MetaKnowledgeGraphServiceTest in two ways:
- This test now writes out all reported nodes and edges to TSV files (if there is a `src/test/resources` directory to write to).
- This test also checks to ensure that `biolink:NamedThing biolink:related_to biolink:NamedThing` is in the list of reported edges. Since we shouldn't be asserting this directly, the presence of this MetaEdge should prove that we "includ[e] all implied ancesestor relationships" as required by https://github.com/NCATSTranslator/ReasonerAPI/commit/e2ed87aa4f02dac55dcbd8eac7e190b8c188fbdd

### CODE REVIEW

**Review by balhoff — APPROVED** [review]
Here I don't think it will cause any harm, but generally writing to disk should be performed in a ZIO.

**Comment by gaurav** [comment]
> Here I don't think it will cause any harm, but generally writing to disk should be performed in a ZIO.

Fair! I'll keep that in mind for next time, although I agree that it won't cause any harm here because:
- We silently don't write out these files if the expected directory (`src/resources/...`) does not exist.
- If the directory exists but is not writeable, this test will fail with an exception, letting the user know something went wrong.

When you say "writing to disk should be performed in a ZIO", do you mean using something like [ZIO.bracket](https://zio.dev/version-1.x/overview/overview_handling_resources/#bracket) to ensure that files are closed correctly and any thrown exceptions are tracked, or something like [`AsynchronousFileChannel` in zio-nio](https://zio.github.io/zio-nio/docs/essentials/essentials_files)?

**Comment by gaurav** [comment]
Aha! Maybe you mean `effectBlockingIO(new PrintWriter(...)).bracketAuto { pw => ... }` as used in:
https://github.com/ExposuresProvider/cam-kp-api/blob/b12f9269207eb7e063d630f100ec6c1e900e055b/src/main/scala/org/renci/cam/MetaKnowledgeGraphService.scala#L28-L31

**Comment by balhoff** [comment]
> Aha! Maybe you mean `effectBlockingIO(new PrintWriter(...)).bracketAuto { pw => ... }` as used in:
> 
> https://github.com/ExposuresProvider/cam-kp-api/blob/b12f9269207eb7e063d630f100ec6c1e900e055b/src/main/scala/org/renci/cam/MetaKnowledgeGraphService.scala#L28-L31

That's probably most robust; it could be put into a utility method to simplify calling code.

**Comment by gaurav** [comment]
> Here I don't think it will cause any harm, but generally writing to disk should be performed in a ZIO.

Fixed in 6076c767e1e1043c!

**Pull request merged**
